apiVersion: apps/v1
kind: Deployment
metadata:
  name: wonderful-v2
  namespace: default
  labels:
    app: wonderful
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wonderful
      version: v2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%        # Allows 25% additional Pods during update
      maxUnavailable: 25%  # Allows 25% Pods to be unavailable during update
  template:
    metadata:
      labels:
        app: wonderful
        version: v2
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

