apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-11-18T09:36:43Z"
  generation: 1
  labels:
    app: wonderful
    version: v1
  name: wonderful-v1
  namespace: default
  resourceVersion: "981929"
  uid: e9c22542-0f8b-40fb-8e3c-412af460314d
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wonderful
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wonderful
        version: v1
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

