apiVersion: apps/v1
kind: Deployment
metadata:
  name: wonderful-v1
  namespace: default
  labels:
    app: wonderful
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wonderful
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%        # Percentage or absolute number of Pods to add during updates
      maxUnavailable: 25%  # Percentage or absolute number of Pods that can be unavailable during updates
  template:
    metadata:
      labels:
        app: wonderful
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

