apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: wonderful
    version: v2
spec:
  type: NodePort
  selector:
    version: v2
  ports:
    - protocol: TCP
      port: 80        # The port the service exposes
      targetPort: 80  # The port your app listens on
      nodePort: 32330   # Optional. Specify a custom NodePort (default range: 30000-32767)

